"use client";
import { useEffect, useState, type FormEvent } from "react";
import { formatPaiseAsInr } from "@/lib/money";
import type { PaymentMethod, ReceivableApi } from "@/lib/types";

const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata" }).format(new Date());
export function ReceivablesManager({ onChanged }: { onChanged: () => void }) {
  const [items, setItems] = useState<ReceivableApi[]>([]); const [personName, setPersonName] = useState(""); const [amount, setAmount] = useState(""); const [givenDate, setGivenDate] = useState(today()); const [expectedReturnDate, setExpectedReturnDate] = useState(""); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>("cash"); const [error, setError] = useState<string | null>(null);
  const load = async () => { const r = await fetch("/api/receivables"); if (r.ok) setItems((await r.json()).receivables); };
  useEffect(() => { load(); }, []);
  async function add(e: FormEvent) { e.preventDefault(); const amountPaise = Math.round(Number(amount) * 100); if (!personName || !Number.isFinite(amountPaise) || amountPaise <= 0) { setError("Enter a person and valid amount."); return; } const r = await fetch("/api/receivables", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ personName, amountPaise, givenDate, expectedReturnDate: expectedReturnDate || null, paymentMethod }) }); if (!r.ok) { setError("Could not save this receivable."); return; } setPersonName(""); setAmount(""); setExpectedReturnDate(""); setError(null); await load(); onChanged(); }
  async function markReturned(item: ReceivableApi) { const returnedDate = window.prompt("Return date (YYYY-MM-DD)", today()); if (!returnedDate) return; const r = await fetch(`/api/receivables/${item.id}/return`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ returnedDate, paymentMethod }) }); if (r.ok) { await load(); onChanged(); } }
  return <section className="mb-6 rounded-xl border border-slate-200 bg-white p-4"><div className="mb-3"><h2 className="text-sm font-semibold text-slate-700">Money lent & refundable deposits</h2><p className="text-xs text-slate-500">Tracked as money you expect back, not an expense.</p></div>{items.map((item) => <div key={item.id} className="mb-2 flex items-center justify-between gap-2 rounded-lg bg-slate-50 p-3"><div><p className="text-sm font-medium">{item.personName} · {formatPaiseAsInr(item.amountPaise)}</p><p className="text-xs text-slate-500">Given {item.givenDate}{item.expectedReturnDate ? ` · expected ${item.expectedReturnDate}` : ""} · {item.status}</p></div>{item.status === "pending" && <button type="button" onClick={() => markReturned(item)} className="rounded-md bg-emerald-600 px-2 py-1.5 text-xs font-medium text-white">Mark returned</button>}</div>)}<form onSubmit={add} className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5"><input required value={personName} onChange={e => setPersonName(e.target.value)} placeholder="Friend / person" className="rounded-md border p-2 text-sm"/><input required type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="Amount (INR)" className="rounded-md border p-2 text-sm"/><input type="date" value={givenDate} onChange={e => setGivenDate(e.target.value)} className="rounded-md border p-2 text-sm"/><input type="date" value={expectedReturnDate} onChange={e => setExpectedReturnDate(e.target.value)} className="rounded-md border p-2 text-sm"/><button className="rounded-md bg-amber-600 p-2 text-sm font-medium text-white">Add money lent</button></form>{error && <p className="mt-2 text-xs text-red-600">{error}</p>}</section>;
}
